server:
  port: 10010
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
  forward-headers-strategy: framework
spring:
  # 强制使用代码配置,不要使用配置文件.
  flyway:
    check-location: true
    enabled: false
    encoding: utf-8
    locations: classpath:db
    validate-on-migrate: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PWD}
    database: ${REDIS_DATABASE:0}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${MYSQL_URL:localhost:3306}/template_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:123456}
          hikari:
            minIdle: 5
            maxPoolSize: 10
        userDb:
          url: jdbc:mysql://${MYSQL_URL:localhost:3306}/template_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:123456}
          hikari:
            minIdle: 5
            maxPoolSize: 10
  application:
    name: bussines-service
mybatis-plus:
  configuration:
    database-id: MYSQL
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: session
    default-statement-timeout: 25000
    cache-enabled: true
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: simple
    safe-row-bounds-enabled: false
    default-enum-type-handler: org.pettyfox.base.web.typehandler.BaseEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    org.pettyfox.*: debug
project:
  build:
    date: '@maven.build.timestamp@'
  version: '@project.version@'
dubbo:
  scan:
    base-packages: org.pettyfox.framework
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: bussines-service
  protocol:
    port: 25688
    host: 127.0.0.1
