server:
  port: 9099
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
  forward-headers-strategy: framework
spring:
  # 强制使用代码配置,不要使用配置文件.
  flyway:
    check-location: true
    enabled: false
    encoding: utf-8
    locations: classpath:db
    validate-on-migrate: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${MYSQL_URL}/t_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ${MYSQL_USERNAME}
          password: ${MYSQL_PASSWORD}
          hikari:
            minIdle: 5
            maxPoolSize: 10
        userDb:
          url: jdbc:mysql://${MYSQL_URL}/t_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ${MYSQL_USERNAME}
          password: ${MYSQL_PASSWORD}
          hikari:
            minIdle: 5
            maxPoolSize: 10
mybatis-plus:
  configuration:
    database-id: MYSQL
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: session
    default-statement-timeout: 25000
    cache-enabled: true
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: simple
    safe-row-bounds-enabled: false
    default-enum-type-handler: org.pettyfox.base.web.typehandler.BaseEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.eface.*: debug
project:
  build:
    date: '@maven.build.timestamp@'
  version: '@project.version@'
